-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 12:16:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scannergic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scannergic` ;

-- -----------------------------------------------------
-- Schema scannergic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scannergic` DEFAULT CHARACTER SET utf8 ;
USE `scannergic` ;

-- -----------------------------------------------------
-- Table `scannergic`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`ingredient` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueIngredients` (`name` ASC, `id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`product` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueProducts` (`name` ASC, `id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`allergen` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`allergen` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueAllergen` (`name` ASC, `id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`product_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`product_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`product_has_ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `Ingredients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_has_Ingredients_Ingredients1_idx` (`Ingredients_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Ingredients_Products_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Ingredients_Products`
    FOREIGN KEY (`Products_id`)
    REFERENCES `scannergic`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Ingredients_id`)
    REFERENCES `scannergic`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`ingredient_has_allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`ingredient_has_allergen` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`ingredient_has_allergen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Ingredients_id` INT NOT NULL,
  `Allergen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ingredients_has_Allergen_Allergen1_idx` (`Allergen_id` ASC) VISIBLE,
  INDEX `fk_Ingredients_has_Allergen_Ingredients1_idx` (`Ingredients_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredients_has_Allergen_Ingredients1`
    FOREIGN KEY (`Ingredients_id`)
    REFERENCES `scannergic`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Allergen_Allergen1`
    FOREIGN KEY (`Allergen_id`)
    REFERENCES `scannergic`.`allergen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
