-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 14:09:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scannergic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scannergic` ;

-- -----------------------------------------------------
-- Schema scannergic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scannergic` DEFAULT CHARACTER SET utf8 ;
USE `scannergic` ;

-- -----------------------------------------------------
-- Table `scannergic`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`ingredient` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`product` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `UPC` DECIMAL(13,0) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UPC_UNIQUE` (`UPC` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`allergen` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`allergen` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`product_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`product_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`product_has_ingredient` (
  `product_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `ingredient_id`),
  INDEX `fk_product_has_ingredient_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_product_has_ingredient_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_ingredient_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `scannergic`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `scannergic`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scannergic`.`ingredient_has_allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scannergic`.`ingredient_has_allergen` ;

CREATE TABLE IF NOT EXISTS `scannergic`.`ingredient_has_allergen` (
  `ingredient_id` INT NOT NULL,
  `allergen_id` INT NOT NULL,
  PRIMARY KEY (`ingredient_id`, `allergen_id`),
  INDEX `fk_ingredient_has_allergen_allergen1_idx` (`allergen_id` ASC) VISIBLE,
  INDEX `fk_ingredient_has_allergen_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_has_allergen_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `scannergic`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_allergen_allergen1`
    FOREIGN KEY (`allergen_id`)
    REFERENCES `scannergic`.`allergen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
